name: smartboiler
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  sleek_circular_slider: ^2.0.1
  firebase_core: ^3.0.0
  firebase_database: ^11.0.0
  json_serializable: ^6.3.1
  json_annotation: ^4.6.0
  build_runner: ^2.2.0
  dio: ^5.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  firebase_auth: ^5.0.0
  google_sign_in: ^6.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:  
  uses-material-design: true
  assets:
    - assets/